<?php
/**
 * Created by PhpStorm.
 * User: yoyo
 * Date: 2018/4/13
 * Time: 下午3:38
 */
namespace backend\widgets\ztree\assets;

use yii\web\AssetBundle;

class ZtreeAssets extends AssetBundle
{
//    public function init()
//    {
//        parent::init(); // TODO: Change the autogenerated stub
//    }

    public $sourcePath = __DIR__;

    public $css = [
        'css/zTreeStyle/zTreeStyle.css'
    ];
    public $js = [
        'js/jquery.ztree.core.js',
        'js/jquery.ztree.excheck.js',
        'js/jquery.ztree.exedit.js',
        'js/jquery.ztree.exhide.js',
    ];
    public $depends = [
        'yii\web\JqueryAsset'
    ];

}